# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-15 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField()),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
