# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-15 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0007_auto_20171015_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
